//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        internal static string ABOUTUS {
            get {
                return ResourceManager.GetString("ABOUTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been created successfuly, please check you mentioned email to verify the account..
        /// </summary>
        internal static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin is not allowed for this operation..
        /// </summary>
        internal static string AdminNotAllowedForThisOperation {
            get {
                return ResourceManager.GetString("AdminNotAllowedForThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already booked this deal..
        /// </summary>
        internal static string AlreadyBookedDeal {
            get {
                return ResourceManager.GetString("AlreadyBookedDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deal is already favourite for you..
        /// </summary>
        internal static string AlreadyFavouriteDeal {
            get {
                return ResourceManager.GetString("AlreadyFavouriteDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This salon is already present in your interest list..
        /// </summary>
        internal static string AlreadyInterested {
            get {
                return ResourceManager.GetString("AlreadyInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saloon4K.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        internal static string CONTACTUS {
            get {
                return ResourceManager.GetString("CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent, we will contact you shortly..
        /// </summary>
        internal static string ContactUsMessageSent {
            get {
                return ResourceManager.GetString("ContactUsMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAL.
        /// </summary>
        internal static string DEAL {
            get {
                return ResourceManager.GetString("DEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Booked.
        /// </summary>
        internal static string DealBooked {
            get {
                return ResourceManager.GetString("DealBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Favourite.
        /// </summary>
        internal static string DealFavourite {
            get {
                return ResourceManager.GetString("DealFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deal is booked successfuly..
        /// </summary>
        internal static string DealIsBooked {
            get {
                return ResourceManager.GetString("DealIsBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deal is favourite for you now..
        /// </summary>
        internal static string DealIsFavourite {
            get {
                return ResourceManager.GetString("DealIsFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTORY.
        /// </summary>
        internal static string DIRECTORY {
            get {
                return ResourceManager.GetString("DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username already exists..
        /// </summary>
        internal static string DuplicateUsername {
            get {
                return ResourceManager.GetString("DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgError.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country..
        /// </summary>
        internal static string InvalidCountry {
            get {
                return ResourceManager.GetString("InvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password..
        /// </summary>
        internal static string InvalidUsernamPassword {
            get {
                return ResourceManager.GetString("InvalidUsernamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first to complete the action..
        /// </summary>
        internal static string LoginToCompleteAction {
            get {
                return ResourceManager.GetString("LoginToCompleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My SALON 4K.
        /// </summary>
        internal static string MySALON4K {
            get {
                return ResourceManager.GetString("MySALON4K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available for this graph..
        /// </summary>
        internal static string NoDataIsAvailable {
            get {
                return ResourceManager.GetString("NoDataIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        internal static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match, please try again..
        /// </summary>
        internal static string PasswordNotSame {
            get {
                return ResourceManager.GetString("PasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP UP.
        /// </summary>
        internal static string POPUP {
            get {
                return ResourceManager.GetString("POPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        internal static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfuly..
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact system administrator..
        /// </summary>
        internal static string RecordError {
            get {
                return ResourceManager.GetString("RecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfuly..
        /// </summary>
        internal static string RecordSave {
            get {
                return ResourceManager.GetString("RecordSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This salon has been added in your interest list..
        /// </summary>
        internal static string SalonIsInterested {
            get {
                return ResourceManager.GetString("SalonIsInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salons.
        /// </summary>
        internal static string Salons {
            get {
                return ResourceManager.GetString("Salons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Booked.
        /// </summary>
        internal static string SaloonBooked {
            get {
                return ResourceManager.GetString("SaloonBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Interested.
        /// </summary>
        internal static string SaloonInterested {
            get {
                return ResourceManager.GetString("SaloonInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaudiArabia.
        /// </summary>
        internal static string SaudiArabia {
            get {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgSuccess.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitedArabEmirates.
        /// </summary>
        internal static string UAE {
            get {
                return ResourceManager.GetString("UAE", resourceCulture);
            }
        }
    }
}
